2020-07-20 16:24:07 - root - INFO - Connection with MYSQL ready
2020-07-20 16:24:07 - root - INFO - Database was created successfully
2020-07-20 16:24:07 - root - INFO - Tables were created successfully
2020-07-20 16:24:21 - root - INFO - Browser connect to URL
2020-07-20 16:24:23 - root - INFO - Search for job title
2020-07-20 16:24:23 - root - INFO - Search for job location
2020-07-20 16:24:30 - root - ERROR - No popup to close
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 28, in close_popup
    pop_up = self.browser.find_element_by_xpath(cst.POP_UP_XPATH)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[contains(@class,'modal_main')]//span[@class='SVGInline modal_closeIcon']

2020-07-20 16:24:42 - root - INFO - Browser connect to new URL
2020-07-20 16:24:56 - root - ERROR - No popup to close
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 28, in close_popup
    pop_up = self.browser.find_element_by_xpath(cst.POP_UP_XPATH)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[contains(@class,'modal_main')]//span[@class='SVGInline modal_closeIcon']

2020-07-20 16:24:56 - root - INFO - Succeed to catch number of available pages
2020-07-20 16:25:05 - root - INFO - Succeed to close popup
2020-07-20 16:25:05 - root - INFO - Start to collect all data from page
2020-07-20 16:25:28 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 42, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 16:25:28 - root - INFO - Insert company to DB successfully
2020-07-20 16:25:28 - root - INFO - Insert job to DB successfully
2020-07-20 16:25:51 - root - ERROR - There is a problem with catching text from xpath
Traceback (most recent call last):
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/scraper.py", line 42, in catch_optional_text_value_by_xpath
    text_value = self.browser.find_element_by_xpath(x_path).text
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Sheryl/PycharmProjects/Itc_data_mining/data_mining/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //div[@class="infoEntity"]//label[text()="Competitors"]//following-sibling::*

2020-07-20 16:25:51 - root - INFO - Insert company to DB successfully
2020-07-20 16:25:51 - root - INFO - Insert job to DB successfully
2020-07-20 16:26:14 - root - INFO - Insert company to DB successfully
2020-07-20 16:26:14 - root - INFO - Get information from DB
2020-07-20 16:26:31 - root - INFO - Browser connect to URL
